module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'feature',
        'fix',
        'refactor',
        'docs',
        'build',
        'test',
        'ci',
        'chore',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'components',
        'cli',
        'button',
        'card',
        'input',
        'select',
        'checkbox',
        'radio',
        'switch',
        'slider',
        'avatar',
        'badge',
        'alert',
        'dialog',
        'sheet',
        'toast',
        'utils',
        'docs',
        'config',
        'deps',
      ],
    ],
    'scope-case': [2, 'always', 'lower-case'],
    'subject-case': [0],
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'type-case': [2, 'always', 'lower-case'],
    'type-empty': [2, 'never'],
  },
};
